---
DB:
  Driver: mysql
  Source: ty:123@tcp(localhost:3306)/gopherty?charset=utf8
  # ShowSQL: true
  MaxOpenConns: 100
  MaxIdleConns: 3
  Cached: 200
Server:
  Address: :10000
  CertFile: ""
  KeyFile: ""
GatewayServer: 
  Address: :10001
Secret: 
  Access: wings15
  Refresh: wings247
Logger: 
  Level: debug
  Encoding: console
  TimeFormat: "2006-01-02 15:04:05.000"
  Development: true
  LogsPath: ""