---
DB:
  Driver: mysql
  Source: ty:123@tcp(localhost:3306)/gopherty?charset=utf8
  # ShowSQL: true
  MaxOpenConns: 100
  MaxIdleConns: 3
  Cached: 200
Server:
  Address: :10000
  Release: false
  CertFile: ""
  KeyFile: ""
Logger: 
  Level: debug
  Encoding: console
  Development: false
  LogsPath: "wings.log"